# Generated by Django 6.0.4 on 2026-04-21 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
