# Generated by Django 6.0.4 on 2026-04-21 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0003_alter_badge_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.CharField(choices=[('EXHIBITOR', 'Exhibitor'), ('VISITOR', 'Visitor'), ('VIP', 'VIP')], max_length=20),
        ),
    ]
