# Generated by Django 6.0.4 on 2026-04-21 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0004_alter_badge_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor', to='exhibitor.event'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exhibitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
