# Generated by Django 6.0.4 on 2026-04-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0005_alter_exhibitor_event_alter_exhibitor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
