# Generated by Django 6.0.4 on 2026-04-22 04:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0006_alter_attendee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='badge',
            name='ticket_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
