# Generated by Django 6.0.4 on 2026-04-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0007_remove_badge_qr_code_badge_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='pass_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
