# Generated by Django 6.0.4 on 2026-04-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0009_alter_attendee_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='country_of_residence',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='nationality',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
