# Generated by Django 6.0.4 on 2026-04-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0010_alter_attendee_country_of_residence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='ticket_class',
        ),
    ]
