# Generated by Django 6.0.4 on 2026-04-25 04:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0011_remove_badge_ticket_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='invite_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
