# Generated by Django 6.0.4 on 2026-05-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0013_alter_attendee_invite_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='exhibitor_pass_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='vip_pass_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='visitor_pass_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
