# Generated by Django 6.0.4 on 2026-05-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0014_exhibitor_exhibitor_pass_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='pass_limit',
        ),
    ]
