# Generated by Django 6.0.4 on 2026-05-13 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0015_remove_exhibitor_pass_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_type',
        ),
    ]
