# Generated by Django 6.0.4 on 2026-05-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0016_remove_badge_badge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='attendee_type',
            field=models.CharField(choices=[('EXHIBITOR', 'Exhibitor'), ('VISITOR', 'Visitor'), ('VIP', 'VIP')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], db_index=True, default='PENDING', max_length=20),
        ),
    ]
