# Generated by Django 6.0.4 on 2026-05-15 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0017_alter_attendee_attendee_type_alter_attendee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='country_of_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
