# Generated by Django 6.0.4 on 2026-05-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0018_alter_attendee_country_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
