# Generated by Django 6.0.4 on 2026-06-04 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0019_alter_attendee_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplimentaryInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('invite_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('attendee_type', models.CharField(choices=[('EXHIBITOR', 'Exhibitor'), ('VISITOR', 'Visitor'), ('VIP', 'VIP')], default='VISITOR', max_length=20)),
                ('usage_limit', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complimentary_invitations', to='exhibitor.exhibitor')),
            ],
        ),
    ]
