# Generated by Django 6.0.4 on 2026-06-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0020_complimentaryinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='complimentaryinvitation',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
