# Generated by Django 6.0.4 on 2026-06-04 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0021_complimentaryinvitation_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='complimentary_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_attendees', to='exhibitor.complimentaryinvitation'),
        ),
    ]
