# Generated by Django 6.0.4 on 2026-06-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0022_attendee_complimentary_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='complimentaryinvitation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
