# Generated by Django 6.0.4 on 2026-06-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibitor', '0023_complimentaryinvitation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='complimentaryinvitation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='complimentaryinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('PERSONALIZED', 'Personalized')], default='GENERIC', max_length=20),
        ),
    ]
